//Đăng ký đăng nhập
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//error
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//user
export const FETCH_USERS = 'FETCH_USERS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

//station
export const FETCH_STATIONS = 'FETCH_STATIONS';

//schedule
export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_FAIL = 'CREATE_SCHEDULE_FAIL';
export const EDIT_SCHEDULE_SUCCESS = 'EDIT_SCHEDULE_SUCCESS';
export const EDIT_SCHEDULE_FAIL = 'EDIT_SCHEDULE_FAIL';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL';

//route
export const FETCH_ROUTES = 'FETCH_ROUTES';
export const CREATE_ROUTE_SUCCESS = 'CREATE_ROUTE_SUCCESS';
export const CREATE_ROUTE_FAIL = 'CREATE_ROUTE_FAIL';
export const EDIT_ROUTE_SUCCESS = 'EDIT_ROUTE_SUCCESS';
export const EDIT_ROUTE_FAIL = 'EDIT_ROUTE_FAIL';
export const UPDATE_ROUTE_SUCCESS = 'UPDATE_ROUTE_SUCCESS';
export const UPDATE_ROUTE_FAIL = 'UPDATE_ROUTE_FAIL';
export const DELETE_ROUTE_SUCCESS = 'DELETE_ROUTE_SUCCESS';
export const DELETE_ROUTE_FAIL = 'DELETE_ROUTE_FAIL';

//train
export const FETCH_TRAINS = 'FETCH_TRAINS';

//invoice
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_TICKETS = 'FETCH_TICKETS';
export const CANCEL_TICKET_SUCCESS = 'CANCEL_TICKET_SUCCESS';
export const CANCEL_TICKET_FAIL = 'CANCEL_TICKET_SUCCESS';
